apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: targetgroupbindings.ryangraham.internal
spec:
  group: ryangraham.internal
  names:
    kind: TargetGroupBinding
    plural: targetgroupbindings
    singular: targetgroupbinding
    shortNames:
      - tgb
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                serviceRef:
                  type: object
                  description: "Reference to the Kubernetes service whose endpoints should be registered in the target group"
                  properties:
                    name:
                      type: string
                      description: "Name of the service to be referenced"
                    namespace:
                      type: string
                      description: "Namespace of the service to be referenced"
                  required:
                    - name
                    - namespace

                targetGroupSelector:
                  type: object
                  description: "Selector to find the AWS target group by tags"
                  properties:
                    tags:
                      type: object
                      additionalProperties:
                        type: string
                      description: "Map of AWS tag keys and values used to select the target group"
                  required:
                    - tags
              required:
                - serviceRef
                - targetGroupSelector

            status:
              type: object
              properties:
                targetGroupARN:
                  type: string
                  description: "ARN of the AWS target group that was selected"
                lastSyncTime:
                  type: string
                  format: date-time
                  description: "Timestamp of the last successful sync"
                registeredIPs:
                  type: array
                  description: "List of IPs that are currently registered in the target group"
                  items:
                    type: string
                    format: ipv4
              required:
                - targetGroupARN
                - lastSyncTime
  additionalPrinterColumns:
    - name: Service
      type: string
      jsonPath: .spec.serviceRef.name
    - name: Target Group ARN
      type: string
      jsonPath: .status.targetGroupARN
    - name: Last Sync
      type: string
      format: date-time
      jsonPath: .status.lastSyncTime
