apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: targetgroupbindings.ryangraham.internal
spec:
  group: ryangraham.internal
  names:
    kind: TargetGroupBinding
    plural: targetgroupbindings
    singular: targetgroupbinding
    shortNames:
      - tgb
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetGroupARN:
                  type: string
                  description: "The ARN of the AWS target group"
                  x-kubernetes-validations:
                    - rule: "self.startsWith('arn:')"
                      message: "TargetGroupARN must be a valid AWS ARN."
                nodeSelector:
                  type: object
                  additionalProperties:
                    type: string
                  description: "Node selector for matching nodes"
            status:
              type: object
              properties:
                currentNodes:
                  type: array
                  items:
                    type: string
                  description: "List of nodes currently registered in the target group"
                totalNodes:
                  type: integer
                  description: "Total number of nodes matching the node selector"
                registeredNodes:
                  type: integer
                  description: "Number of nodes currently registered in the target group"
                lastSyncTime:
                  type: string
                  format: date-time
                  description: "The last time the target group was synchronized with Kubernetes nodes"
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Target Group ARN
          type: string
          jsonPath: .spec.targetGroupARN
        - name: Total Nodes
          type: integer
          jsonPath: .status.totalNodes
        - name: Registered Nodes
          type: integer
          jsonPath: .status.registeredNodes
        - name: Last Sync
          type: string
          format: date-time
          jsonPath: .status.lastSyncTime
