apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "target-group-controller.fullname" . }}-cluster-role
  labels:
    app.kubernetes.io/name: {{ include "target-group-controller.name" . }}
    helm.sh/chart: {{ include "target-group-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups:
      - "ryangraham.internal"
    resources:
      - targetgroupbindings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "ryangraham.internal"
    resources:
      - targetgroupbindings/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
      - apiGroups:
        - "coordination.k8s.io"
        resources:
        - leases
        verbs:
        - create
  - apiGroups:
    - "coordination.k8s.io"
    resources:
    - leases
    resourceNames:
    - target-group-controller-leader
    verbs:
    - get
    - update
    - patch
