apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "target-group-controller.fullname" . }}-cluster-role-binding
  labels:
    app.kubernetes.io/name: {{ include "target-group-controller.name" . }}
    helm.sh/chart: {{ include "target-group-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "target-group-controller.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "target-group-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
